name: Build Docker image

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

permissions:
  contents: read

env:
  image: apognu/playground

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: apognu
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check if image exists
        id: image-check
        run: |
          trap 'echo "build=$?" >> "$GITHUB_OUTPUT"; exit 0' EXIT
          docker manifest inspect ${{ env.image }}:${{ github.sha }}

      - name: Build Docker image
        if: steps.image-check.outputs.build == '1'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.image }}:${{ github.sha }}

      - name: Tag image with 'latest'
        if: ${{ inputs.environment == 'staging' }}
        run: docker buildx imagetools create --tag ${{ env.image }}:latest ${{ env.image }}:${{ github.sha }}

      - name: Tag image with tag ${{ github.ref_name }}
        if: ${{ inputs.environment == 'production' }}
        run: docker buildx imagetools create --tag ${{ env.image }}:latest ${{ env.image }}:${{ github.ref_name }}
