name: Deploy production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        run: echo Build...

  docker:
    needs: [build]
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      environment: production
