name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PRERELEASE: ${{ contains(github.ref_name, '-rc.') }}
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ inputs.tag }}
          make_latest: env.PRERELEASE == 'false'
          generate_release_notes: true
          draft: env.PRERELEASE == 'true'
          prerelease: env.PRERELEASE == 'true'
          files: |
            artifact

      - name: Publish prerelease
        uses: softprops/action-gh-release@v3
        if: env.PRERELEASE == 'true'
        with:
          name: ${{ inputs.tag }}
          make_latest: false
          draft: false
          prerelease: true
